### PR TITLE
fix: fix CJS compatibility

### LINKED ISSUE #2602: v3.3.6 causes `TypeError: layoutEngine is not a function` in @react-pdf/renderer when using Next.js
**Describe the bug**
After upgrading from v3.3.5 to v3.3.6, my Next.js app's `react-pdf` server-side generations are failing with:

```
TypeError: layoutEngine is not a function
    at Object.<anonymous> (/vercel/path0/node_modules/@react-pdf/layout/lib/index.cjs:308:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at mod.require (/vercel/path0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/vercel/path0/node_modules/@react-pdf/renderer/lib/react-pdf.cjs:14:22)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
```

Rolling back to v3.3.5 makes the issue go away.

**To Reproduce**

Minimal repro available here: https://stackblitz.com/edit/stackblitz-starters-rxmqpt?file=app%2Fapi%2Fbuild-pdf%2FMyDocument.tsx

**Expected behavior**
`react-pdf` should not crash.

**Screenshots**

image

**Desktop (please complete the following information):**

- OS: All
- Browser: Chrome
- React-pdf version: v3.3.6

### LINKED ISSUE #2603: ESM Build Broken
The latest updates to support ESM builds has broken default exports. Specifically for @react-pdf/textkit. 

Sorry, I know this isn't a lot to go on, sitting in rocking chair with infant...

Will try to follow-up with more details.

Also, this only impacts people using cjs/require

### PR DESCRIPTION
**Pull request by wojtekmaj**
Closes #2602
Closes #2603

Sorry about that!

We will also need some sanity checks to prevent this from happening in the future.

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Before:

```
wmaj@MacBook-Air layout % yarn build && node lib/index.cjs
yarn run v1.22.19
$ rimraf ./lib && rollup -c
(node:69215) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:69215) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

src/index.js → lib/index.js, lib/index.cjs...
created lib/index.js, lib/index.cjs in 1.2s
✨  Done in 1.88s.
/Users/wmaj/Projekty/Open source projects/diegomura-react-pdf/packages/layout/lib/index.cjs:308
var engine$1 = layoutEngine(engines$1);
               ^

TypeError: layoutEngine is not a function
    at Object.<anonymous> (/Users/wmaj/Projekty/Open source projects/diegomura-react-pdf/packages/layout/lib/index.cjs:308:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

Node.js v20.9.0
```

After:

```
wmaj@MacBook-Air layout % yarn build && node lib/index.cjs
yarn run v1.22.19
$ rimraf ./lib && rollup -c
(node:69580) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:69580) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

src/index.js → lib/index.js, lib/index.cjs...
created lib/index.js, lib/index.cjs in 923ms
✨  Done in 1.31s.
```

**Review by diegomura — APPROVED** [review]
utACK

Thanks!
