### ISSUE TITLE
@react-pdf/textkit@5.0.1 font.layout is not a function

### ISSUE THREAD

**Issue by ShiraDC** [diegomura/react-pdf#2990]
**Describe the bug**
After upgrading @react-pdf/renderer from 3.4.4 to 4.1.5 which updates the react-pdf/textkit to 5.0.1 I get the error:
`TypeError: font.layout is not a function`

**To Reproduce**
I cannot open my PDF, as it won't render. Didn't make any changes to my code since the last version.
I am adding fonts to my pdf:
`Font.register({ 
family: 'Manrope',
  fonts: [
    { src: manrope },
    { src: manropeLight, fontWeight: 'light' },
    { src: manropeMedium, fontWeight: 'medium' },
    { src: manropeSemibold, fontWeight: 'bold' },
    { src: manropeBold, fontWeight: 'ultrabold' }
  ]
})
Font.register({
  family: 'Roboto Slab',
  fonts: [{ src: robotoSlab }, { src: robotoSlabBold, fontWeight: 'bold' }]
})`

 and implement them on each page:
 `const styles = StyleSheet.create({
  page: {
    backgroundColor: '#f7f7f7',
    color: colorPalette.dcPurple,
    position: 'relative',
    fontFamily: 'Manrope'
  },
  main: {
    backgroundColor: colorPalette.dcDark,
    paddingTop: '30pt'
  }
})`

**Expected behavior**
PDF will render as before

**Screenshots**
![Screenshot 2024-12-01 at 12 13 09](https://github.com/user-attachments/assets/c830c1af-655e-4f8c-9d7b-4dd18ddd8833)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser chrome
- React-pdf version 4.1.5

**Comment by diegomura** [comment]
I'll need that font to test. Can you provide it?

**Comment by pranavavva** [comment]
Hi, we're also having this issue but we're using the Arial font in our PDFs. We're on @react-pdf/renderer 3.4.2 and react-pdf 8.0.2.

**Comment by ShiraDC** [comment]
> I'll need that font to test. Can you provide it?

Hi, I added one example in the first comment, but the family font is `Manrope` and `Roboto Slab`

**Comment by santrajyadav196** [comment]
I am also facing font related issue in  @react-pdf/renderer2.1.0 with font Poppins sant nato. Pls let me know @diegomura how to fix this. Thanks in advance.

**Comment by G-C0der** [comment]
I get the same error "TypeError: font.layout is not a function", using @react-pdf/renderer 3.0.0. I also tried 3.4.4 which worked for OP and also multiple other versions with many downloads.
Is there already a solution to this issue? Any help is highly appreciated.
