### ISSUE TITLE
JSX-RUNTIME ERROR

### ISSUE THREAD

**Issue by shuvamgrad** [diegomura/react-pdf#2221]
./node_modules/@react-pdf/renderer/lib/react-pdf.browser.es.js
--
Cannot find module: 'react/jsx-runtime'. Make sure this package is installed.
You can install this package by running: yarn add react/jsx-runtime.

I am getting this error while build react app in docker container which was working file.
Error on version:"@react-pdf/renderer": "^3.1.2" and also after upgrading to "@react-pdf/renderer": "^3.1.6"

**Comment by jeetiss** [comment]
update `react` to `16.14.0`, or `17.0.0`, or `18.0.0`

**Comment by shuvamgrad** [comment]
works with 16.14.0. Thank you.

**Comment by qlaire** [comment]
@jeetiss I'm unable to upgrade to 16.14.0 at this time. Currently on 16.9.0. Is there an older version that I can use that would be compatible?

**Comment by qlaire** [comment]
found this PR: https://github.com/diegomura/react-pdf/pull/2211

so installed library at the version just before (@react-pdf/renderer@3.1.5) and that solved it

**Comment by eduardpauliuc** [comment]
@jeetiss can the [documentation](https://react-pdf.org/compatibility#:~:text=with%20React%2016%20(-,16.8.0,-or%20later)%2C%20React) be updated?  It currently states that `react 16.8.0` is still compatible, which is no longer true.
