### ISSUE TITLE
TypeError: aa is not a function 

### ISSUE THREAD

**Issue by Smirow** [diegomura/react-pdf#2164]
**Describe the bug**
`3.1.1` seems broken (on Node at least), throws `TypeError: aa is not a function` when rendering.

**To Reproduce**
I'll work on a minimal repro

**Expected behavior**
Should work as `3.1.0`

**Comment by EvHaus** [comment]
I also started getting this after upgrading from @react-pdf/renderer v3.0.3 to v3.1.1. It appears to impact `renderToStream(...)`, however `pdf(...).toBuffer()` still works fine.

**Comment by jeetiss** [comment]
@Smirow do I understand right that `v3.1.0` works on node but `v3.1.1` doesn't?

**Comment by Smirow** [comment]
@jeetiss yes 3.1.0 seems to fork fine.

**Comment by jeetiss** [comment]
@Smirow could you provide a repo with reproduction? seems like it is a weird bug around esm default and commonjs exports interop but i cant reproduce it to fix and test for the future

**Comment by Smirow** [comment]
@jeetiss yes sure, when I'll get near a keyboard, probably later today.

**Comment by Smirow** [comment]
@jeetiss here you go https://stackblitz.com/edit/sveltejs-kit-template-default-h6r82t, you'll find the relevant code in `/src/routes/+server.ts`

**Comment by WalberthLopes** [comment]
Same error here.

**Comment by jeetiss** [comment]
I create a fix, could you help me with testing?

- just download this file: [react-pdf-renderer-3.1.2.tgz](https://github.com/diegomura/react-pdf/files/10534635/react-pdf-renderer-3.1.2.tgz)
- install it like `npm i ./path-to/react-pdf-renderer-3.1.2.tgz`(or `yarn add ./path-to/react-pdf-renderer-3.1.2.tgz`)
- run your project as before

**Comment by cris-ms** [comment]
Same here. I will try this.

> I create a fix, could you help me with testing?
> 
> * just download this file: [react-pdf-renderer-3.1.2.tgz](https://github.com/diegomura/react-pdf/files/10534635/react-pdf-renderer-3.1.2.tgz)
> * install it like `npm i ./path-to/react-pdf-renderer-3.1.2.tgz`(or `yarn add ./path-to/react-pdf-renderer-3.1.2.tgz`)
> * run your project as before
> * ...
> * it should work (I hope smiling_face_with_tear)

**Comment by Smirow** [comment]
@jeetiss seems to work on my end.

**Comment by jeetiss** [comment]
Released `v3.1.2`

**Comment by Smirow** [comment]
Thanks, `v3.1.2` working as expected.

**Comment by jeetiss** [comment]
> Hi, thanks for the quick fix! Is there a test that could catch this type of error?

Nope, you can create e2e tests for esm and cjs entries. Current tests use transpaler and this error is possible
