### ISSUE TITLE
index.js:1 Error: unsupported number: -Infinity

### ISSUE THREAD

**Issue by swipe9** [diegomura/react-pdf#1629]
Just updated to 2.0.21 and getting this one.

Not able to figure out where this is happening? Working fine in 1.6.12

Please help.

`index.js:1 Error: unsupported number: -Infinity
    at Function.number (pdfkit.browser.es.js:353)
    at pdfkit.browser.es.js:1944
    at Array.map (<anonymous>)
    at PDFDocument.transform (pdfkit.browser.es.js:1943)
    at PDFDocument.translate (pdfkit.browser.es.js:1949)
    at renderText (renderText.js:233)
    at _curryN.js:34
    at _arity.js:10
    at cond.js:42
    at _arity.js:10
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _arity.js:10
    at renderNode.js:80
    at Array.forEach (<anonymous>)
    at renderNode.js:72
    at when (when.js:32)
    at _curry3.js:28
    at f1 (_curry1.js:16)
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _arity.js:10
    at renderNode.js:80
    at Array.forEach (<anonymous>)
    at renderNode.js:72
    at when (when.js:32)
    at _curry3.js:28
    at f1 (_curry1.js:16)
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _pipe.js:3
    at _arity.js:10
    at renderNode.js:80
    at Array.forEach (<anonymous>)
    at index.js:15
    at render (index.js:21)
    at _callee$ (index.js:35)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)`

**Comment by SallesCosta** [comment]
i have the same problem

**Comment by SallesCosta** [comment]
when i erase some 4 or 5 lines of <Text>.. Ok.. i can generate the pdf file.. 
but i need theses 4 or 5 lines

**Comment by LukakHR** [comment]
Had the same error, check your Text components. If you have:

`<Text>undefined</Text> `

you will get that error

**Comment by diegomura** [comment]
That line no longer produces this error

**Comment by swipe9** [comment]
Thank you so much!

**Comment by stefan-dospinescu-spektr** [comment]
This also happens when a block of elements is wrapped. When adding wrapped={false} on container issue goes away.
