### ISSUE TITLE
v3.3.6 causes `TypeError: layoutEngine is not a function` in @react-pdf/renderer when using Next.js

### ISSUE THREAD

**Issue by EvHaus** [diegomura/react-pdf#2602]
**Describe the bug**
After upgrading from v3.3.5 to v3.3.6, my Next.js app's `react-pdf` server-side generations are failing with:

```
TypeError: layoutEngine is not a function
    at Object.<anonymous> (/vercel/path0/node_modules/@react-pdf/layout/lib/index.cjs:308:16)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at mod.require (/vercel/path0/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/vercel/path0/node_modules/@react-pdf/renderer/lib/react-pdf.cjs:14:22)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
```

Rolling back to v3.3.5 makes the issue go away.

**To Reproduce**

Minimal repro available here: https://stackblitz.com/edit/stackblitz-starters-rxmqpt?file=app%2Fapi%2Fbuild-pdf%2FMyDocument.tsx

**Expected behavior**
`react-pdf` should not crash.

**Screenshots**

![image](https://github.com/diegomura/react-pdf/assets/226640/7df0335d-e171-4df1-a2a5-7f2924307696)

**Desktop (please complete the following information):**

- OS: All
- Browser: Chrome
- React-pdf version: v3.3.6

**Comment by iamMohammadAamir** [comment]
I am still getting error, even after update react-pdf/renderer 3.3.6

TypeError: Cannot read property 'Hidden' of undefined
web/node_modules/@react-pdf/layout/lib/index.js:2179:25

**Comment by NCSmit** [comment]
Still getting this error after updating to 3.3.6. 

`"@react-pdf/renderer": "^3.3.6",`

TypeError: layoutEngine is not a function

**Comment by glarivie** [comment]
Same error here, but I'm not using Next.js

**Comment by diegomura** [comment]
Will take a look today

**Comment by NCSmit** [comment]
Downgrading versions does not resolve the error on my end, anyone else ?

**Comment by gino8080** [comment]
Can't get it working anymore! I'm trying also very old versions

**Comment by mrkoch** [comment]
Same error with node and express project

**Comment by mateuszaliyev** [comment]
If you have issues even after downgrading, override `@react-pdf/layout`'s version in your `package.json`.

```json
"overrides": {
  "@react-pdf/layout": "3.10.4"
}
```

pnpm:

```json
"pnpm": {
  "overrides": {
    "@react-pdf/layout": "3.10.4"
  }
},
```

The error states clearly that `layoutEngine` is a function in `@react-pdf/layout` library, a direct dependency of `@react-pdf/renderer`. Unfortunately in `@react-pdf/renderer`'s `package.json` there is a caret (`^`) symbol next to the versions of its dependencies. That means package managers will try to install the newest version of its dependencies, including faulty `@react-pdf/layout`, regardless of which version of `@react-pdf/renderer` you install.

And this is why you should always pin your dependencies.

**Comment by mrkoch** [comment]
Thanks to @mateuszaliyev. I use yarn and have this package.json structure:

```
"dependencies": {
    "@david.kucsai/react-pdf-table": "^0.4.1",
    "@react-pdf/renderer": "3.3.5",
    ....
}
```
Now it's running and building but when i try to generate pdf i got this error:
```
"message":"NodePdf Error: TypeError bidi is not a function ","stack":"TypeError: bidi is not a function
```

**Comment by AbrahamX3** [comment]
I get the same error using the latest version also on Next.js, but doing the following https://github.com/diegomura/react-pdf/issues/2603#issuecomment-1928973440 fixed the issue for me!

**Comment by iamMohammadAamir** [comment]
@AbrahamX3 
Thanks for the update
I don't have resolution inside package.json i just have dependency "@react-pdf/renderer": "3.1.17". all the resolution are part of node-modules of react-pdf renderer.
is there any other way to fix this ?

**Comment by AbrahamX3** [comment]
@iamMohammadAamir I just copy and pasted the resolutions from the comment onto my package.json and ran pnpm install

**Comment by wojtekmaj** [comment]
I have a strong suspicion that it is my fault (specifically, in my PR #2594).

Before:
```js
var layoutEngine = require('@react-pdf/textkit');
// …
function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }
// …
var layoutEngine__default = /*#__PURE__*/_interopDefaultLegacy(layoutEngine);
// …
var engine = layoutEngine__default["default"](engines);
```

after:
```js
var layoutEngine = require('@react-pdf/textkit');
// …
var engine = layoutEngine(engines);
```

It must have something to do with [output.interop](https://rollupjs.org/configuration-options/#output-interop) Rollup option.

But there's one more thing that needs to be resolved to make the new version working and that is jay-peg package exports. Hold tight.

**Comment by dominik992** [comment]
+1

**Comment by iamMohammadAamir** [comment]
@wojtekmaj  Thanks for your help,
When will this fix deploy ?

**Comment by DaveFPath** [comment]
I just updated using ncu (which updated all the version numbers) and I started getting this error. I am not a fan of "rolling back", but I will try it for now. Any update on this issue?

**Comment by krzysztof-stanislawski** [comment]
NPM temporary solution that worked for me:

1. add to package.json:

 ```
"overrides": {
    "@react-pdf/renderer": {
      "version": "3.3.5",
      "@react-pdf/layout": {
        "version": "3.10.4"
      }
    }
  },
```
2. remove 
`node_modules`

3. run 
`npm install`

**Comment by taylorli2000** [comment]
Can anyone else with this issue confirm if this was fixed with 3.3.7? I tried removing lockfile node_modules and running npm i and I get ts build errors still.

**Comment by wojtekmaj** [comment]
What kind of errors? We'll need some logs to be able to even start looking into it.

**Comment by taylorli2000** [comment]
@wojtekmaj I get similar errors to #2559. Mine are TS2323, TS2309, and TS2484.

```
node_modules/@react-pdf/renderer/lib/react-pdf.d.cts:17:10 - error TS2323: Cannot redeclare exported variable 'default'.

17   static default: typeof ReactPDF;
            ~~~~~~~

node_modules/@react-pdf/renderer/lib/react-pdf.d.cts:20:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

20 export = ReactPDF;
   ~~~~~~~~~~~~~~~~~~

node_modules/@react-pdf/renderer/lib/react-pdf.d.cts:53:9 - error TS2323: Cannot redeclare exported variable 'Document'.

53   class Document extends React.Component<
           ~~~~~~~~

node_modules/@react-pdf/renderer/lib/react-pdf.d.cts:101:9 - error TS2323: Cannot redeclare exported variable 'Page'.

101   class Page extends React.Component<React.PropsWithChildren<PageProps>> {}
            ~~~~

node_modules/@react-pdf/renderer/lib/react-pdf.d.cts:125:9 - error TS2323: Cannot redeclare exported variable 'View'.

125   class View extends React.Component<React.PropsWithChildren<ViewProps>> {}

node_modules/@react-pdf/renderer/lib/react-pdf.d.cts:633:3 - error TS2484: Export declaration conflicts with exported declaration of 'Font'.

633   Font,
      ~~~~
```

**Comment by wojtekmaj** [comment]
That is something totally different then. Please file a separate issue so we don't spam people here.

**Comment by iamMohammadAamir** [comment]
For me below solution worked.
add this code in your package.json file 

"resolutions": {
"@react-pdf/layout": "3.10.4"
  }

**Comment by jd-carroll** [comment]
For anyone landing here, you're going to run into: #2624
