### ISSUE TITLE
Cannot render PDF after updating to 2.0.4 from 1.6.16

### ISSUE THREAD

**Issue by pmark019** [diegomura/react-pdf#1206]
When I render a PDF after updating to V2.0, I get this error and I don't know what should be changed.
Based on the documentation, V2.0 should be backwards compatible with V1.0.

> index.js:1 TypeError: element.type is not a function
    at createInstance (createInstance.js:34)
    at resolveChildren (resolvePagination.js:168)
    at evolve (evolve.js:36)
    at Module.f2 (_curry2.js:26)
    at resolveDynamicNodes (resolvePagination.js:183)
    at resolvePagination.js:172
    at Array.map (<anonymous>)
    at resolveChildren (resolvePagination.js:171)
    at evolve (evolve.js:36)
    at Module.f2 (_curry2.js:26)
    at resolveDynamicNodes (resolvePagination.js:183)
    at resolveDynamicPage (resolvePagination.js:194)
    at splitPage (resolvePagination.js:204)
    at paginate (resolvePagination.js:250)
    at resolvePagination (resolvePagination.js:278)
    at _callee$ (asyncCompose.js:60)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)

**Comment by diegomura** [comment]
And it is. Can you provide a snippet so I can replicate this? It seems to be failing when computing dynamic nodes

**Comment by pmark019** [comment]
I finally found the issue. This was because I was using <> tag in render of View.
After changing it to <View>, the issue no longer occurs.
